"""initial registry and corpus schema

Revision ID: 56a19066e66e
Revises: 
Create Date: 2026-09-21 12:47:19.951059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a19066e66e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.Column('is_baseline', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_context')),
    sqlite_strict=True
    )
    op.create_table('data_source',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.Text(), nullable=False),
    sa.Column('adapter_version', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_data_source')),
    sqlite_strict=True
    )
    op.create_table('embedding_slot',
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('entity_key', sa.Text(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('table_name', 'entity_key', name=op.f('pk_embedding_slot')),
    sa.UniqueConstraint('table_name', 'slot', name='uq_slot'),
    sqlite_strict=True
    )
    op.create_table('functional_unit',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('quantity_kind', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('reference_service_life_years', sa.REAL(), nullable=True),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.CheckConstraint("quantity_kind IN ('mass','volume','area','length','count','energy')", name=op.f('ck_functional_unit_quantity_kind')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_functional_unit')),
    sqlite_strict=True
    )
    op.create_table('indicator_family',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_indicator_family')),
    sqlite_strict=True
    )
    op.create_table('provenance',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_provenance')),
    sqlite_strict=True
    )
    op.create_table('registry_release',
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('max_slots', sa.Text(), nullable=False),
    sa.Column('yaml_blob', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('pk_registry_release')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_registry_release_content_hash')),
    sqlite_strict=True
    )
    op.create_table('stakeholder',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.Column('domain_scope_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_stakeholder')),
    sqlite_strict=True
    )
    op.create_table('category',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.Column('functional_unit_key', sa.Text(), nullable=False),
    sa.Column('eligibility_precondition_text', sa.Text(), nullable=False),
    sa.Column('default_context_key', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['default_context_key'], ['context.key'], name=op.f('fk_category_default_context_key_context')),
    sa.ForeignKeyConstraint(['functional_unit_key'], ['functional_unit.key'], name=op.f('fk_category_functional_unit_key_functional_unit')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_category')),
    sa.UniqueConstraint('key', 'functional_unit_key', name='uq_category_fu'),
    sqlite_strict=True
    )
    op.create_table('indicator',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('family_key', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.Column('default_direction', sa.Integer(), nullable=False),
    sa.Column('nominal_justification', sa.Text(), nullable=True),
    sa.Column('is_derived', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.CheckConstraint("unit IS NULL OR value_type = 'continuous'", name=op.f('ck_indicator_unit_continuous_only')),
    sa.CheckConstraint("value_type <> 'nominal' OR default_direction = 0", name=op.f('ck_indicator_nominal_no_direction')),
    sa.CheckConstraint("value_type <> 'nominal' OR nominal_justification IS NOT NULL", name=op.f('ck_indicator_nominal_justified')),
    sa.CheckConstraint("value_type IN ('continuous','ordinal','nominal','boolean')", name=op.f('ck_indicator_value_type')),
    sa.CheckConstraint('default_direction IN (-1,0,1)', name=op.f('ck_indicator_direction')),
    sa.ForeignKeyConstraint(['family_key'], ['indicator_family.key'], name=op.f('fk_indicator_family_key_indicator_family')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_indicator')),
    sqlite_strict=True
    )
    op.create_table('snapshot',
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('registry_version', sa.Text(), nullable=False),
    sa.Column('split_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('filter_spec', sa.Text(), nullable=False),
    sa.Column('row_counts', sa.Text(), nullable=False),
    sa.Column('parquet_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['registry_version'], ['registry_release.version'], name=op.f('fk_snapshot_registry_version_registry_release')),
    sa.PrimaryKeyConstraint('content_hash', name=op.f('pk_snapshot')),
    sqlite_strict=True
    )
    op.create_table('stakeholder_priority',
    sa.Column('stakeholder_key', sa.Text(), nullable=False),
    sa.Column('target_kind', sa.Text(), nullable=False),
    sa.Column('target_key', sa.Text(), nullable=False),
    sa.Column('priority', sa.REAL(), nullable=False),
    sa.CheckConstraint("target_kind IN ('family','indicator')", name=op.f('ck_stakeholder_priority_target_kind')),
    sa.CheckConstraint('priority >= 0.0 AND priority <= 1.0', name=op.f('ck_stakeholder_priority_priority')),
    sa.ForeignKeyConstraint(['stakeholder_key'], ['stakeholder.key'], name=op.f('fk_stakeholder_priority_stakeholder_key_stakeholder')),
    sa.PrimaryKeyConstraint('stakeholder_key', 'target_kind', 'target_key', name=op.f('pk_stakeholder_priority')),
    sqlite_strict=True
    )
    op.create_table('category_context_override',
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('context_key', sa.Text(), nullable=False),
    sa.Column('is_applicable', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.CheckConstraint('is_applicable IN (0,1)', name=op.f('ck_category_context_override_is_applicable')),
    sa.ForeignKeyConstraint(['category_key'], ['category.key'], name=op.f('fk_category_context_override_category_key_category')),
    sa.ForeignKeyConstraint(['context_key'], ['context.key'], name=op.f('fk_category_context_override_context_key_context')),
    sa.PrimaryKeyConstraint('category_key', 'context_key', name=op.f('pk_category_context_override')),
    sqlite_strict=True
    )
    op.create_table('category_indicator',
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('indicator_key', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Integer(), nullable=False),
    sa.Column('relevance_mode', sa.Text(), nullable=False),
    sa.Column('direction_override', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("relevance_mode IN ('always','context_declared')", name=op.f('ck_category_indicator_relevance_mode')),
    sa.CheckConstraint('direction_override IS NULL OR direction_override IN (-1,0,1)', name=op.f('ck_category_indicator_direction_override')),
    sa.ForeignKeyConstraint(['category_key'], ['category.key'], name=op.f('fk_category_indicator_category_key_category')),
    sa.ForeignKeyConstraint(['indicator_key'], ['indicator.key'], name=op.f('fk_category_indicator_indicator_key_indicator')),
    sa.PrimaryKeyConstraint('category_key', 'indicator_key', name=op.f('pk_category_indicator')),
    sa.UniqueConstraint('category_key', 'indicator_key', name='uq_cat_ind'),
    sqlite_strict=True
    )
    op.create_table('category_provenance_weight',
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('provenance_key', sa.Text(), nullable=False),
    sa.Column('weight', sa.REAL(), nullable=False),
    sa.CheckConstraint('weight >= 0.0', name=op.f('ck_category_provenance_weight_weight')),
    sa.ForeignKeyConstraint(['category_key'], ['category.key'], name=op.f('fk_category_provenance_weight_category_key_category')),
    sa.ForeignKeyConstraint(['provenance_key'], ['provenance.key'], name=op.f('fk_category_provenance_weight_provenance_key_provenance')),
    sa.PrimaryKeyConstraint('category_key', 'provenance_key', name=op.f('pk_category_provenance_weight')),
    sqlite_strict=True
    )
    op.create_table('comparison_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('provenance_key', sa.Text(), nullable=False),
    sa.Column('generator_key', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_key'], ['category.key'], name=op.f('fk_comparison_set_category_key_category')),
    sa.ForeignKeyConstraint(['provenance_key'], ['provenance.key'], name=op.f('fk_comparison_set_provenance_key_provenance')),
    sa.ForeignKeyConstraint(['source_key'], ['data_source.key'], name=op.f('fk_comparison_set_source_key_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparison_set')),
    sa.UniqueConstraint('id', 'category_key', name='uq_set_category'),
    sa.UniqueConstraint('source_key', 'external_id', name='uq_source_external'),
    sqlite_strict=True
    )
    with op.batch_alter_table('comparison_set', schema=None) as batch_op:
        batch_op.create_index('ix_set_provenance', ['provenance_key', 'category_key'], unique=False)

    op.create_table('context_declaration',
    sa.Column('context_key', sa.Text(), nullable=False),
    sa.Column('indicator_key', sa.Text(), nullable=False),
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('priority', sa.REAL(), nullable=False),
    sa.Column('is_required', sa.Integer(), nullable=False),
    sa.Column('ideal_value', sa.REAL(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('direction IN (-1,0,1)', name=op.f('ck_context_declaration_direction')),
    sa.CheckConstraint('priority > 0.0 AND priority <= 1.0', name=op.f('ck_context_declaration_priority')),
    sa.ForeignKeyConstraint(['context_key'], ['context.key'], name=op.f('fk_context_declaration_context_key_context')),
    sa.ForeignKeyConstraint(['indicator_key'], ['indicator.key'], name=op.f('fk_context_declaration_indicator_key_indicator')),
    sa.PrimaryKeyConstraint('context_key', 'indicator_key', 'category_key', name=op.f('pk_context_declaration')),
    sqlite_strict=True
    )
    op.create_table('indicator_derivation',
    sa.Column('derived_key', sa.Text(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('coefficient', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['derived_key'], ['indicator.key'], name=op.f('fk_indicator_derivation_derived_key_indicator')),
    sa.ForeignKeyConstraint(['source_key'], ['indicator.key'], name=op.f('fk_indicator_derivation_source_key_indicator')),
    sa.PrimaryKeyConstraint('derived_key', 'source_key', name=op.f('pk_indicator_derivation')),
    sqlite_strict=True
    )
    op.create_table('indicator_level',
    sa.Column('indicator_key', sa.Text(), nullable=False),
    sa.Column('level_key', sa.Text(), nullable=False),
    sa.Column('level_index', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.Column('normalised_position', sa.REAL(), nullable=True),
    sa.Column('is_disqualifying', sa.Integer(), nullable=False),
    sa.CheckConstraint('normalised_position IS NULL OR (normalised_position >= 0.0 AND normalised_position <= 1.0)', name=op.f('ck_indicator_level_position_unit_interval')),
    sa.ForeignKeyConstraint(['indicator_key'], ['indicator.key'], name=op.f('fk_indicator_level_indicator_key_indicator')),
    sa.PrimaryKeyConstraint('indicator_key', 'level_key', name=op.f('pk_indicator_level')),
    sa.UniqueConstraint('indicator_key', 'level_index', name='uq_level_index'),
    sqlite_strict=True
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['category_key'], ['category.key'], name=op.f('fk_product_category_key_category')),
    sa.ForeignKeyConstraint(['source_key'], ['data_source.key'], name=op.f('fk_product_source_key_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('id', 'category_key', name='uq_product_category'),
    sqlite_strict=True
    )
    op.create_table('comparison_set_context',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('context_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['context_key'], ['context.key'], name=op.f('fk_comparison_set_context_context_key_context')),
    sa.ForeignKeyConstraint(['set_id'], ['comparison_set.id'], name=op.f('fk_comparison_set_context_set_id_comparison_set')),
    sa.PrimaryKeyConstraint('set_id', 'context_key', name=op.f('pk_comparison_set_context')),
    sqlite_strict=True
    )
    op.create_table('comparison_set_member',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('local_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_id', 'category_key'], ['product.id', 'product.category_key'], name='fk_member_product_category'),
    sa.ForeignKeyConstraint(['set_id', 'category_key'], ['comparison_set.id', 'comparison_set.category_key'], name='fk_member_set_category'),
    sa.PrimaryKeyConstraint('set_id', 'product_id', name=op.f('pk_comparison_set_member')),
    sa.UniqueConstraint('set_id', 'position', name='uq_set_position'),
    sqlite_strict=True
    )
    with op.batch_alter_table('comparison_set_member', schema=None) as batch_op:
        batch_op.create_index('ix_member_product', ['product_id'], unique=False)

    op.create_table('comparison_set_stakeholder',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('stakeholder_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['comparison_set.id'], name=op.f('fk_comparison_set_stakeholder_set_id_comparison_set')),
    sa.ForeignKeyConstraint(['stakeholder_key'], ['stakeholder.key'], name=op.f('fk_comparison_set_stakeholder_stakeholder_key_stakeholder')),
    sa.PrimaryKeyConstraint('set_id', 'stakeholder_key', name=op.f('pk_comparison_set_stakeholder')),
    sqlite_strict=True
    )
    op.create_table('dataset_split',
    sa.Column('comparison_set_id', sa.Integer(), nullable=False),
    sa.Column('split_key', sa.Text(), nullable=False),
    sa.Column('fold', sa.Text(), nullable=False),
    sa.CheckConstraint("fold IN ('train','val','test')", name=op.f('ck_dataset_split_fold')),
    sa.ForeignKeyConstraint(['comparison_set_id'], ['comparison_set.id'], name=op.f('fk_dataset_split_comparison_set_id_comparison_set')),
    sa.PrimaryKeyConstraint('comparison_set_id', 'split_key', name=op.f('pk_dataset_split')),
    sqlite_strict=True
    )
    op.create_table('indicator_reference_range',
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('indicator_key', sa.Text(), nullable=False),
    sa.Column('ref_low', sa.REAL(), nullable=False),
    sa.Column('ref_high', sa.REAL(), nullable=False),
    sa.Column('scale', sa.Text(), nullable=False),
    sa.Column('shape', sa.Text(), nullable=False),
    sa.Column('ideal_value', sa.REAL(), nullable=True),
    sa.Column('ideal_low', sa.REAL(), nullable=True),
    sa.Column('ideal_high', sa.REAL(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.CheckConstraint("scale <> 'log' OR ref_low > 0", name=op.f('ck_indicator_reference_range_log_positive')),
    sa.CheckConstraint("scale IN ('linear','log')", name=op.f('ck_indicator_reference_range_scale')),
    sa.CheckConstraint("shape <> 'ideal_band' OR (ideal_low IS NOT NULL AND ideal_high IS NOT NULL)", name=op.f('ck_indicator_reference_range_ideal_band')),
    sa.CheckConstraint("shape <> 'ideal_point' OR ideal_value IS NOT NULL", name=op.f('ck_indicator_reference_range_ideal_point')),
    sa.CheckConstraint("shape IN ('monotone','ideal_point','ideal_band')", name=op.f('ck_indicator_reference_range_shape')),
    sa.CheckConstraint('ref_high > ref_low', name=op.f('ck_indicator_reference_range_range_ordered')),
    sa.ForeignKeyConstraint(['category_key', 'indicator_key'], ['category_indicator.category_key', 'category_indicator.indicator_key'], name='fk_range_membership'),
    sa.PrimaryKeyConstraint('category_key', 'indicator_key', name=op.f('pk_indicator_reference_range')),
    sqlite_strict=True
    )
    op.create_table('indicator_value',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('indicator_key', sa.Text(), nullable=False),
    sa.Column('present', sa.Integer(), nullable=False),
    sa.Column('value_num', sa.REAL(), nullable=True),
    sa.Column('level_key', sa.Text(), nullable=True),
    sa.CheckConstraint('(present = 1 AND (value_num IS NOT NULL OR level_key IS NOT NULL)) OR (present = 0 AND value_num IS NULL AND level_key IS NULL)', name=op.f('ck_indicator_value_present_implies_value')),
    sa.CheckConstraint('present IN (0,1)', name=op.f('ck_indicator_value_present')),
    sa.CheckConstraint('value_num IS NULL OR level_key IS NULL', name=op.f('ck_indicator_value_one_value_channel')),
    sa.ForeignKeyConstraint(['indicator_key', 'level_key'], ['indicator_level.indicator_key', 'indicator_level.level_key'], name='fk_value_level'),
    sa.ForeignKeyConstraint(['indicator_key'], ['indicator.key'], name=op.f('fk_indicator_value_indicator_key_indicator')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_indicator_value_product_id_product')),
    sa.PrimaryKeyConstraint('product_id', 'indicator_key', name=op.f('pk_indicator_value')),
    sqlite_strict=True
    )
    with op.batch_alter_table('indicator_value', schema=None) as batch_op:
        batch_op.create_index('ix_indicator_value_indicator', ['indicator_key'], unique=False)

    op.create_table('label_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_set_id', sa.Integer(), nullable=False),
    sa.Column('provenance_key', sa.Text(), nullable=False),
    sa.Column('labeller_key', sa.Text(), nullable=True),
    sa.Column('scale_semantics', sa.Text(), nullable=False),
    sa.Column('method_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("scale_semantics IN ('within_set_relative','absolute_reference')", name=op.f('ck_label_set_scale_semantics')),
    sa.ForeignKeyConstraint(['comparison_set_id'], ['comparison_set.id'], name=op.f('fk_label_set_comparison_set_id_comparison_set')),
    sa.ForeignKeyConstraint(['provenance_key'], ['provenance.key'], name=op.f('fk_label_set_provenance_key_provenance')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_set')),
    sa.UniqueConstraint('comparison_set_id', 'provenance_key', 'labeller_key', name='uq_labelset_identity'),
    sqlite_strict=True
    )
    op.create_table('label',
    sa.Column('label_set_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pref', sa.REAL(), nullable=False),
    sa.Column('conf', sa.REAL(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.CheckConstraint('conf IS NULL OR (conf >= 0.0 AND conf <= 1.0)', name=op.f('ck_label_conf_unit_interval')),
    sa.CheckConstraint('pref >= 0.0 AND pref <= 1.0', name=op.f('ck_label_pref_unit_interval')),
    sa.ForeignKeyConstraint(['label_set_id'], ['label_set.id'], name=op.f('fk_label_label_set_id_label_set')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_label_product_id_product')),
    sa.PrimaryKeyConstraint('label_set_id', 'product_id', name=op.f('pk_label')),
    sqlite_strict=True
    )
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.create_index('ix_label_product', ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_index('ix_label_product')

    op.drop_table('label')
    op.drop_table('label_set')
    with op.batch_alter_table('indicator_value', schema=None) as batch_op:
        batch_op.drop_index('ix_indicator_value_indicator')

    op.drop_table('indicator_value')
    op.drop_table('indicator_reference_range')
    op.drop_table('dataset_split')
    op.drop_table('comparison_set_stakeholder')
    with op.batch_alter_table('comparison_set_member', schema=None) as batch_op:
        batch_op.drop_index('ix_member_product')

    op.drop_table('comparison_set_member')
    op.drop_table('comparison_set_context')
    op.drop_table('product')
    op.drop_table('indicator_level')
    op.drop_table('indicator_derivation')
    op.drop_table('context_declaration')
    with op.batch_alter_table('comparison_set', schema=None) as batch_op:
        batch_op.drop_index('ix_set_provenance')

    op.drop_table('comparison_set')
    op.drop_table('category_provenance_weight')
    op.drop_table('category_indicator')
    op.drop_table('category_context_override')
    op.drop_table('stakeholder_priority')
    op.drop_table('snapshot')
    op.drop_table('indicator')
    op.drop_table('category')
    op.drop_table('stakeholder')
    op.drop_table('registry_release')
    op.drop_table('provenance')
    op.drop_table('indicator_family')
    op.drop_table('functional_unit')
    op.drop_table('embedding_slot')
    op.drop_table('data_source')
    op.drop_table('context')
    # ### end Alembic commands ###
